---
title: Teaching
---

**SY27: Intelligent Vehicles** | November 2021-January 2022
<br />
Supervision of student project: Autonomous navigation and development of a multi-sensor localization solution with integrity control.
<br />
<u>Keywords</u>: Localization, Integrity, Perception, Control

**SY27: Intelligent Vehicles** | November 2022-January 2023
<br />
Supervision of student project: Autonomous navigation with human-machine interaction through a joystick simulatin a drive-by-wire system.
<br />
<u>Keywords</u>: Drive-by-wire, Interaction, Perception, Control


**SY02: Statistics** | September 2021-January-2022, September 2022-January 2023
Program: Fundamentals of inferential statistics, estimation and confidence intervals, parametric tests, linear regression.

**SY27: Intelligent Vehicles** | November 2023, November 2024
<br />
Lectured on perception for autonomous vehicle localization, multi-modal automatic annotation, and YOLOv7 training.
<br />

**ARS4: Estimation for Autonomous Navigatio** | December 2024-January 2025
<br />
Proposed a project centered on localization using lidar-detected poles and traffic signs. The students were tasked with designing a multi-sensor fusion approach that integrated GNSS, lidar measurements associated with mapped elements, and vehicle kinematics. The project began with simulated data without any data association step, progressing to experiments with real-world data. They implemented and evaluated Extended and Unscented Kalman Filters to achieve improved localization accuracy and consistency.
<br />
